-- ============================================================
-- V2__student_samvidha_schema.sql — Student & Samvidha Ingestion Schema
-- Compatible with PostgreSQL (Supabase) and H2 in-memory
-- ============================================================

-- Student profiles table
CREATE TABLE IF NOT EXISTS student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    roll_no VARCHAR(20) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    department VARCHAR(80),
    year_of_study INT,
    semester INT,
    section VARCHAR(10),
    mentor_name VARCHAR(120),
    mentor_cabin VARCHAR(100),
    overall_attendance DOUBLE PRECISION DEFAULT 0.0,
    consent_given BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_roll_no UNIQUE (roll_no),
    CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Subject-wise attendance table
CREATE TABLE IF NOT EXISTS student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    subject_code VARCHAR(30) NOT NULL,
    subject_name VARCHAR(150) NOT NULL,
    attended_classes INT NOT NULL DEFAULT 0,
    total_classes INT NOT NULL DEFAULT 0,
    percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_profile FOREIGN KEY (student_profile_id) REFERENCES student_profiles(id) ON DELETE CASCADE
);

-- Student weekly timetable slots
CREATE TABLE IF NOT EXISTS student_timetables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    day_of_week INT NOT NULL, -- 0=Monday ... 5=Saturday
    time_slot_start VARCHAR(5) NOT NULL, -- e.g. "09:00"
    time_slot_end VARCHAR(5) NOT NULL,   -- e.g. "09:50"
    subject_code VARCHAR(30),
    subject_name VARCHAR(150) NOT NULL,
    room VARCHAR(80) NOT NULL,
    faculty_name VARCHAR(120),
    CONSTRAINT fk_timetable_profile FOREIGN KEY (student_profile_id) REFERENCES student_profiles(id) ON DELETE CASCADE
);

-- Student continuous internal evaluation (CIE) marks
CREATE TABLE IF NOT EXISTS student_marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    subject_code VARCHAR(30) NOT NULL,
    subject_name VARCHAR(150) NOT NULL,
    cie1 DOUBLE PRECISION,
    cie2 DOUBLE PRECISION,
    internal_total DOUBLE PRECISION,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_marks_profile FOREIGN KEY (student_profile_id) REFERENCES student_profiles(id) ON DELETE CASCADE
);

-- Indexes for fast query lookup
CREATE INDEX IF NOT EXISTS idx_student_roll ON student_profiles (roll_no);
CREATE INDEX IF NOT EXISTS idx_attendance_profile ON student_attendance (student_profile_id);
CREATE INDEX IF NOT EXISTS idx_timetable_profile_day ON student_timetables (student_profile_id, day_of_week);
CREATE INDEX IF NOT EXISTS idx_marks_profile ON student_marks (student_profile_id);
