-- ============================================================
-- V4__student_labs_and_notices.sql — Lab submissions & Samvidha circulars/events
-- ============================================================

CREATE TABLE IF NOT EXISTS student_lab_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL REFERENCES student_profiles(id) ON DELETE CASCADE,
    subject_code VARCHAR(20) NOT NULL,
    subject_name VARCHAR(150) NOT NULL,
    experiment_name VARCHAR(200) NOT NULL,
    due_date VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    marks_obtained DOUBLE PRECISION,
    max_marks DOUBLE PRECISION DEFAULT 10.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_student_lab_profile ON student_lab_submissions(student_profile_id);

CREATE TABLE IF NOT EXISTS samvidha_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    notice_date VARCHAR(50),
    category VARCHAR(50) NOT NULL DEFAULT 'ACADEMIC',
    link_url VARCHAR(500),
    description VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_samvidha_notices_category ON samvidha_notices(category);
