-- ============================================================
-- V5__onboarding_chat_memory_and_weakness.sql
-- Onboarding survey, Persistent Conversation Memory & Topic Analytics
-- ============================================================

-- 1. Onboarding Survey Table
CREATE TABLE IF NOT EXISTS student_onboarding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    semester INT,
    branch VARCHAR(100),
    section VARCHAR(20),
    enrolled_courses VARCHAR(1000),
    difficult_subjects VARCHAR(1000),
    college_goals VARCHAR(500),
    technical_interests VARCHAR(500),
    clubs_activities VARCHAR(500),
    preferred_notification_times VARCHAR(200),
    monitored_telegram_groups VARCHAR(500),
    check_in_frequency VARCHAR(50) DEFAULT 'DAILY_BRIEF',
    mood_check_ins_allowed BOOLEAN NOT NULL DEFAULT TRUE,
    samvidha_connected BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_onboarding_user ON student_onboarding(user_id);

-- 2. Add onboarding_completed flag to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;

-- 3. Persistent Chat Sessions Table
CREATE TABLE IF NOT EXISTS chat_sessions (
    id VARCHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL DEFAULT 'New Conversation',
    summary_memory TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_updated ON chat_sessions(user_id, updated_at DESC);

-- 4. Persistent Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL, -- 'user' | 'assistant'
    content TEXT NOT NULL,
    mode VARCHAR(20) DEFAULT 'text',
    agent_type VARCHAR(50) DEFAULT 'general_assistant',
    nav_result_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user ON chat_messages(user_id, created_at DESC);

-- 5. Student Topics Asked (Lightweight Weakness Detection)
CREATE TABLE IF NOT EXISTS student_topics_asked (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject VARCHAR(150) NOT NULL,
    topic VARCHAR(150) NOT NULL,
    query_text VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_topics_asked_user_created ON student_topics_asked(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topics_asked_user_topic ON student_topics_asked(user_id, topic);
