-- ============================================================
-- V6__telegram_events_and_notifications.sql
-- Telegram Event Intelligence, Extracted Circulars & Priority Notifications
-- ============================================================

-- 1. Extracted Events & Official Circulars Table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_telegram_group_id BIGINT,
    source_telegram_message_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    raw_text TEXT,
    has_image BOOLEAN NOT NULL DEFAULT FALSE,
    image_url VARCHAR(500),
    event_date VARCHAR(100),
    event_time VARCHAR(100),
    location VARCHAR(255),
    organizer VARCHAR(255),
    target_semester INT,
    target_branch VARCHAR(100),
    target_section VARCHAR(20),
    target_audience_raw VARCHAR(255),
    is_mandatory BOOLEAN NOT NULL DEFAULT FALSE,
    registration_deadline TIMESTAMP WITH TIME ZONE,
    action_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_events_mandatory ON events(is_mandatory);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_target ON events(target_semester, target_branch);

-- 2. Student Event Priority Notifications Table
CREATE TABLE IF NOT EXISTS student_event_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL, -- 'IMMEDIATE_ALERT', 'UPCOMING_REMINDER'
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_for TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON student_event_notifications(user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_event ON student_event_notifications(event_id);
